language: node_js
node_js:
  - "stable"
install:
  - npm i
cache:
  directories:
    - node_modules
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE DATABASE visitafrica;" -U postgres
  - npm run migrate
script:
  - npm test
after_success:
  - npm run coverage
  