language: node_js
node_js:
  - 12.14.1
before_install:
  - npm install sequelize-cli -g
install:
  - npm install
before-script:
  - npm add sequelize-cli
services:
  - postgresql
before_script:
  - psql -c 'create database visitAfrica_test;' -U postgres
script:
  - npm test
after_script:
  - npm run coveralls
notifications:
  email: false
sudo: false
