language: node_js
node_js:
  - "stable"
before_install:
  - npm install sequelize-cli -g
services:
  - postgresql
  env:
  global:
  - NODE_ENV=test  

before_script:
  - psql -c 'CREATE DATABASE teamwork;' -U postgres
cache: npm
install: npm install
script:
  - npm test
after_success:
- npm run coveralls
